# basic options
title: singhscorner-blog
author: Taran Kalra
email: tarankalra@gmail.com
description: Thoughts on fluid dynamics modelling and HPC 
github_username:  tarankalra-usgs

header_pages:
  - about.md
  - portfolio.md
  
# Build settings
markdown: kramdown
theme: minima


