# basic options
title: Computing Scientist
author: GitHub User
email: tarankalra@gmail.com
description: A wonderful site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
