# basic options
title: singhscorner-blog
author: Taran Kalra
email: tarankalra@gmail.com
description: Thoughts on fluid dynamics and HPC 
github_username:  tarankalra-usgs

# Build settings
markdown: kramdown
theme: minima
