# basic options
title: singhscorner-blog
author: Taran Kalra
email: tarankalra@gmail.com
description: Thoughts on fluid dynamics modelling and HPC 
github_username:  tarankalra-usgs
linkedin_username: tarandeep-singh-kalra-82674811
researchgate_username: Tarandeep_Kalra2

header_pages:
  - about.md
  - portfolio.md

google_analytics: UA-124255809-1


# Build settings
markdown: kramdown
theme: minima


